// Query to check if system node pools have at least 2 nodes
resources
| where type =~ "microsoft.containerservice/managedclusters"
| extend agentPoolProfiles = properties.agentPoolProfiles
| mv-expand agentPoolProfiles
| where agentPoolProfiles.mode =~ "System"
| where toint(agentPoolProfiles.['count']) < 2
| project name, resourceGroup, subscriptionId, poolName = agentPoolProfiles.name, nodeCount = agentPoolProfiles.['count']
